import type { Metadata } from 'next';
import localFont from 'next/font/local';
import SideNavbar from '@/components/side-navbar/side-navbar';
import { Toaster } from 'react-hot-toast';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="relative min-h-screen min-w-full font-mono">
          <aside className="fixed left-0 top-0 z-50 h-screen">
            <SideNavbar />
          </aside>

          <main className="responsive-container min-h-screen w-full scroll-smooth bg-secondary-100">
            <section className="section flex-center z-0 mx-auto h-full space-y-5 border-x border-secondary-200 bg-secondary-50">
              {children}
            </section>
          </main>
          <Toaster position="top-center" reverseOrder={true} />
        </main>
      </body>
    </html>
  );
}
